### ISSUE TITLE
Homepage URL on PyPI broken

### ISSUE THREAD

**Issue by zoni** [ByteInternet/amqpconsumer#8]
The link to the homepage at https://pypi.python.org/pypi/amqpconsumer/1.6 links to https://github.com/ByteInternet/amqpconsumer, but this should be https://github.com/ByteInternet/python-events/.

**Comment by gertjanol** [comment]
No, it should be the other way around: we're in the process of renaming https://github.com/ByteInternet/python-events/ to amqpconsumer. But there are some dependencies on the original repo that need to be fixed.

**Comment by zoni** [comment]
This has fixed.
